version: '3'
name: "mariadb-pma"

services:
  mariadb:
    container_name: mariadb
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: app
      MYSQL_PASSWORD: password
      MARIADB_RANDOM_ROOT_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: mariadb
      PMA_USER: app
      PMA_PASSWORD: password
    depends_on:
      - mariadb

volumes:
  db_data: